{{- if .Values.txSender.enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.txSender.name }}
  labels:
    {{ include "linea.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.txSender.name }}
  {{- with .Values.txSender.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.txSender.replicas | default 1 }}

  selector:
    matchLabels:
      app: {{ .Values.txSender.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.txSender.name }}
      {{- with .Values.txSender.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      containers:
        - name: {{ .Values.txSender.name }}
          image: "{{ .Values.txSender.image.repository }}:{{ .Values.txSender.image.tag }}"
          imagePullPolicy: IfNotPresent

          {{- if .Values.txSender.resources }}
          resources:
            {{- toYaml .Values.txSender.resources | nindent 12 }}
          {{- end }}

          {{- if .Values.txSender.customLivenessProbe }}
          livenessProbe: {{- omit .Values.txSender.customLivenessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.global.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}

          {{- if .Values.txSender.customReadinessProbe }}
          readinessProbe: {{- omit .Values.txSender.customReadinessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.global.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.global.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}

          env:
            {{- include "linea.env" .Values.txSender.env | nindent 12 }}
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.txSender.secrets.secretName }}
                  key: privateKey
                  optional: false
            - name: TO_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.txSender.secrets.secretName }}
                  key: toAddress
                  optional: false
            - name: RPC_URL
              value: "http://{{ include "linea.fullname" . }}-{{ .Values.besu.name }}-svc:{{ .Values.txSender.rpc.port }}"
            - name: INTERVAL_SECONDS
              value: "{{ .Values.txSender.interval }}"
            - name: AMOUNT_WEI
              value: "{{ .Values.txSender.amount }}"

{{- end }}
