{{- if .Values.ethstats.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linea.fullname" . }}-ethstats-svc
  labels:
    {{ include "linea.labels" . | nindent 4 }}
    app.kubernetes.io/component: ethstats
spec:
  type: {{ .Values.ethstats.service.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.ethstats.service.port }}
      targetPort: {{ .Values.ethstats.service.port }}
      name: http
  selector:
    app: {{ include "linea.name" . }}
    component: ethstats
{{- end }}
