apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.besu.name }}-config
data:
  config.toml: |-
{{ .Files.Get "files/config/besu/config.toml" | indent 4 }}

  log4j.xml: |-
{{ .Files.Get "files/config/besu/log4j.xml" | indent 4 }}

  genesis.json: |-
{{ .Files.Get "files/config/common/genesis.json" | indent 4 }}

  tracelimits.toml: |-
{{ .Files.Get "files/config/common/tracelimits.toml" | indent 4 }}

  denylist.txt: |-
{{ .Files.Get "files/config/sequencer/denylist.txt" | indent 4 }}
