{{- if .Values.sequencer.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "linea.fullname" . }}-sequencer-pdb
  labels:
    {{ include "linea.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "linea.name" . }}
      component: sequencer
{{- end }}

