{{- if .Values.sequencer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linea.fullname" . }}-sequencer-svc
  labels:
    {{ include "linea.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
spec:
  type: {{ .Values.sequencer.service.type | default "ClusterIP" }}
  ports:
    - name: metrics
      port: {{ .Values.sequencer.service.portMetrics }}
      targetPort: {{ .Values.sequencer.service.portMetrics }}
    - name: p2p
      port: 30303
      targetPort: 30303
  selector:
    app: {{ include "linea.name" . }}
    component: sequencer
{{- end }}
