{{- if .Values.sequencer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}-svc
  labels:
    {{ include "linea.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.sequencer.name }}
spec:
  clusterIP: "None"
  type: {{ .Values.sequencer.service.type | default "ClusterIP" }}
  ports:
    - name: json-rpc
      port: {{ .Values.sequencer.service.rpcPort }}
      targetPort: {{ .Values.sequencer.service.rpcPort }}
    - name: engine
      port: {{ .Values.sequencer.service.enginePort }}
      targetPort: {{ .Values.sequencer.service.enginePort }}
    - name: ws
      port: {{ .Values.sequencer.service.wsPort }}
      targetPort: {{ .Values.sequencer.service.wsPort }}
    - name: p2p
      port: {{ .Values.sequencer.service.p2pPort }}
      targetPort: {{ .Values.sequencer.service.p2pPort }}
    - name: metrics
      port: {{ .Values.sequencer.service.metricsPort }}
      targetPort: {{ .Values.sequencer.service.metricsPort }}
  selector:
    app: {{ include "linea.name" . }}
    component: {{ .Values.sequencer.name }}
{{- end }}
