{{- if .Values.sequencer.enabled }}
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}
  labels:
    {{ include "linea.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.sequencer.name }}
  {{- with .Values.sequencer.statefulsetAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  serviceName: {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}-svc
  replicas: {{ .Values.sequencer.replicas | default 1 }}

  selector:
    matchLabels:
      app: {{ include "linea.name" . }}
      component: {{ .Values.sequencer.name }}
  template:
    metadata:
      labels:
        app: {{ include "linea.name" . }}
        component: {{ .Values.sequencer.name }}
      {{- with .Values.sequencer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.sequencer.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.sequencer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: sequencer
          image: "{{ .Values.sequencer.image.repository }}:{{ .Values.sequencer.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}

          command:
            - "besu-untuned"

          args:
            - "--ethstats=ws://besu-node:12345@{{ include "linea.fullname" . }}-{{ .Values.ethstats.name }}-svc:3000"
            - "--config-file=/var/lib/besu/config.toml"
            - "--node-private-key-file=/var/lib/besu/key"

          ports:
            - name: json-rpc
              containerPort: {{ .Values.sequencer.service.rpcPort }}
            - name: engine
              containerPort: {{ .Values.sequencer.service.enginePort }}
            - name: ws
              containerPort: {{ .Values.sequencer.service.wsPort }}
            - name: p2p
              containerPort: {{ .Values.sequencer.service.p2pPort }}
            - name: metrics
              containerPort: {{ .Values.sequencer.service.metricsPort }}

          {{- if .Values.sequencer.customLivenessProbe }}
          livenessProbe: {{- omit .Values.sequencer.customLivenessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.global.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}

          {{- if .Values.sequencer.customReadinessProbe }}
          readinessProbe: {{- omit .Values.sequencer.customReadinessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.global.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.global.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}

          env:
            {{- include "linea.env" .Values.sequencer.env | nindent 12 }}
            - name: LOG4J_CONFIGURATION_FILE
              value: /var/lib/besu/log4j.xml

          volumeMounts:
            - name: config
              mountPath: /var/lib/besu/config.toml
              subPath: config.toml

            - name: config
              mountPath: /var/lib/besu/log4j.xml
              subPath: log4j.xml

            - name: config
              mountPath: /var/lib/besu/traces-limits.toml
              subPath: tracelimits.toml

            - name: config
              mountPath: /var/lib/besu/genesis.json
              subPath: genesis.json

            - name: config
              mountPath: /var/lib/besu/deny-list.txt
              subPath: denylist.txt

            - name: {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}-data
              mountPath: /opt/besu/data

            - name: key
              mountPath: /var/lib/besu/key
              subPath: key

      volumes:
        - name: config
          configMap:
            name: {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}-config
        - name: key
          secret:
            secretName: {{ .Values.sequencer.p2pKeySecretName }}

  volumeClaimTemplates:
    - metadata:
        name: {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.sequencer.persistence.size }}
        {{- if .Values.sequencer.persistence.storageClass }}
        storageClassName: {{ .Values.sequencer.persistence.storageClass | quote }}
        {{- else }}
        storageClassName: null
        {{- end }}
{{- end }}
