{{- if .Values.metrics.serviceMonitor.enabled }}

{{/* Sequencer Metrics */}}
{{- if .Values.sequencer.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}-sm
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default "monitoring" }}
  labels:
    release: {{ .Values.metrics.serviceMonitor.releaseLabel | default "monitoring" }}
    {{ include "linea.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.metrics.serviceMonitor.additionalLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "linea.name" . }}
      app.kubernetes.io/component: {{ .Values.sequencer.name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}


{{/* Maru Metrics */}}
{{- if .Values.maru.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.maru.name }}-sm
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default "monitoring" }}
  labels:
    release: {{ .Values.metrics.serviceMonitor.releaseLabel | default "monitoring" }}
    {{ include "linea.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.metrics.serviceMonitor.additionalLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "linea.name" . }}
      app.kubernetes.io/component: {{ .Values.maru.name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}


{{/* Besu Metrics */}}
{{- if .Values.besu.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.besu.name }}-sm
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default "monitoring" }}
  labels:
    release: {{ .Values.metrics.serviceMonitor.releaseLabel | default "monitoring" }}
    {{ include "linea.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.metrics.serviceMonitor.additionalLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "linea.name" . }}
      app.kubernetes.io/component: {{ .Values.besu.name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}

{{- end }}
