apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.maru.name }}-config
data:
  config.toml: |-
{{ tpl (.Files.Get "files/config/maru/config.toml.tpl") . | indent 4 }}

  log4j.xml: |-
{{ .Files.Get "files/config/maru/log4j.xml" | indent 4 }}

  genesis.json: |-
{{ .Files.Get "files/config/maru/genesis.json" | indent 4 }}
