{{- if .Values.maru.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "linea.fullname" . }}-{{ .Values.maru.name }}
  labels:
    {{ include "linea.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.maru.name }}
  {{- with .Values.maru.statefulsetAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "linea.fullname" . }}-{{ .Values.maru.name }}-svc
  replicas: {{ .Values.maru.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "linea.name" . }}
      component: {{ .Values.maru.name }}
  template:
    metadata:
      labels:
        app: {{ include "linea.name" . }}
        component: {{ .Values.maru.name }}
      {{- with .Values.maru.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.maru.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.maru.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
      - name: wait-for-sequencer
        image: curlimages/curl:7.85.0
        command: ["sh","-c","until nc -z {{ include "linea.fullname" . }}-{{ .Values.sequencer.name }}-svc {{ .Values.sequencer.service.metricsPort }}; do sleep 1; done"]
      
      - name: copy-log4j
        image: busybox:1.36
        command: ["sh", "-c", "cp /config/log4j.xml /writable/log4j.xml && chmod 666 /writable/log4j.xml"]
        volumeMounts:
          - name: config
            mountPath: /config
          - name: writable-config
            mountPath: /writable

      containers:
        - name: maru
          image: "{{ .Values.maru.image.repository }}:{{ .Values.maru.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}

          env:
            {{- include "linea.env" .Values.maru.env | nindent 12 }}

          command:
            - "java"
            - "-Dlog4j2.configurationFile=/tmp/log4j.xml"
            - "-jar"
            - "maru.jar"
            - "--maru-genesis-file"
            - "configs/genesis.json"
            - "--config"
            - "configs/config.toml"

          ports:
            - name: http
              containerPort: {{ .Values.maru.service.httpPort }}
            - name: metrics
              containerPort: {{ .Values.maru.service.metricsPort }}

          {{- if .Values.maru.customLivenessProbe }}
          livenessProbe: {{- omit .Values.maru.customLivenessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.global.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}

          {{- if .Values.maru.customReadinessProbe }}
          readinessProbe: {{- omit .Values.maru.customReadinessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.global.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.global.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: config
              mountPath: /opt/consensys/maru/configs/config.toml
              subPath: config.toml

            - name: config
              mountPath: /opt/consensys/maru/configs/genesis.json
              subPath: genesis.json

            - name: writable-config
              mountPath: /tmp

            - name: {{ include "linea.fullname" . }}-{{ .Values.maru.name }}-data
              mountPath: /opt/consensys/maru/data

            - name: key
              mountPath: /opt/consensys/maru/key
              subPath: key

      volumes:
        - name: config
          configMap:
            name: {{ include "linea.fullname" . }}-{{ .Values.maru.name }}-config
        - name: writable-config
          emptyDir: {}
        - name: key
          secret:
            secretName: {{ .Values.maru.p2pKeySecretName }}

  volumeClaimTemplates:
    - metadata:
        name: {{ include "linea.fullname" . }}-{{ .Values.maru.name }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.maru.persistence.size }}
        {{- if .Values.maru.persistence.storageClass }}
        storageClassName: {{ .Values.maru.persistence.storageClass | quote }}
        {{- else }}
        storageClassName: null
        {{- end }}
{{- end }}
